import { notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { PolicyNav } from '@/components/policy/policy-nav'
import { DisclaimerBanner } from '@/components/layout/disclaimer-banner'
import { Badge } from '@/components/ui/badge'
import { ChevronLeft } from 'lucide-react'
import { formatDate, policyTypeLabel, DISCLAIMER } from '@/lib/utils'
import type { PolicySummary, Question } from '@/types'
import { PrintButton } from './print-button'

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const { data: policy } = await supabase.from('policies').select('*').eq('id', id).eq('user_id', user!.id).single()
  if (!policy) notFound()

  const { data: summary } = await supabase.from('policy_summaries').select('*').eq('policy_id', id).single() as { data: PolicySummary | null }
  const { data: questions } = await supabase.from('questions').select('*').eq('policy_id', id).eq('user_id', user!.id).order('created_at', { ascending: false }).limit(20) as { data: Question[] | null }

  return (
    <div className="min-h-screen">
      <div className="bg-white border-b border-slate-200 print:hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3">
          <Link href={`/policies/${id}`} className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-900">
            <ChevronLeft className="h-4 w-4" /> Back to overview
          </Link>
        </div>
        <PolicyNav policyId={id} />
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="flex items-center justify-between mb-8 print:hidden">
          <h1 className="text-2xl font-bold text-slate-900">Policy Report</h1>
          <PrintButton />
        </div>

        {/* Report content */}
        <div id="report-content" className="space-y-8">
          <div className="text-center border-b border-slate-200 pb-8">
            <h1 className="text-3xl font-bold text-slate-900 mb-2">Insurance Policy Report</h1>
            <p className="text-slate-500">{policy.policy_nickname}</p>
            <p className="text-xs text-slate-400 mt-2">Generated by Understand Cover &middot; {new Date().toLocaleDateString('en-GB')}</p>
          </div>

          {summary && (
            <>
              <section>
                <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">Policy Overview</h2>
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <div><span className="text-slate-400">Type:</span> <span className="font-medium">{policyTypeLabel(policy.policy_type)}</span></div>
                  <div><span className="text-slate-400">Insurer:</span> <span className="font-medium">{summary.overview_json.insurer ?? 'Not found'}</span></div>
                  <div><span className="text-slate-400">Policyholder:</span> <span className="font-medium">{summary.overview_json.policyholder ?? 'Not found'}</span></div>
                  <div><span className="text-slate-400">Period:</span> <span className="font-medium">{summary.overview_json.policy_period ?? 'Not found'}</span></div>
                  <div><span className="text-slate-400">Start date:</span> <span className="font-medium">{formatDate(policy.start_date)}</span></div>
                  <div><span className="text-slate-400">End date:</span> <span className="font-medium">{formatDate(policy.end_date)}</span></div>
                </div>
              </section>

              {summary.coverage_json?.length > 0 && (
                <section>
                  <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">What&apos;s Covered</h2>
                  <ul className="space-y-2">
                    {summary.coverage_json.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm">
                        <Badge variant="covered" className="mt-0.5 shrink-0">{item.status}</Badge>
                        <div>
                          <span className="font-medium">{item.title}</span>
                          <span className="text-slate-500 ml-2">{item.explanation}</span>
                          {item.page > 0 && <span className="text-slate-400 ml-2">(Page {item.page})</span>}
                        </div>
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {summary.exclusions_json?.length > 0 && (
                <section>
                  <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">What&apos;s Not Covered</h2>
                  <ul className="space-y-2">
                    {summary.exclusions_json.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm">
                        <Badge variant="excluded" className="mt-0.5 shrink-0">{item.status}</Badge>
                        <div>
                          <span className="font-medium">{item.title}</span>
                          <span className="text-slate-500 ml-2">{item.explanation}</span>
                          {item.page > 0 && <span className="text-slate-400 ml-2">(Page {item.page})</span>}
                        </div>
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {summary.limits_json?.length > 0 && (
                <section>
                  <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">Limits &amp; Excess</h2>
                  <ul className="space-y-2">
                    {summary.limits_json.map((limit, i) => (
                      <li key={i} className="text-sm">
                        <span className="font-medium">{limit.title}:</span>{' '}
                        <span className="text-blue-700 font-bold">{limit.amount}</span>{' '}
                        <span className="text-slate-500">— {limit.context}</span>
                        {limit.page > 0 && <span className="text-slate-400 ml-1">(Page {limit.page})</span>}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {summary.risk_flags_json?.length > 0 && (
                <section>
                  <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">Risk Flags</h2>
                  <ul className="space-y-3">
                    {summary.risk_flags_json.map((flag, i) => (
                      <li key={i} className="text-sm">
                        <div className="flex items-center gap-2 mb-0.5">
                          <Badge variant={flag.level === 'High' ? 'excluded' : flag.level === 'Medium' ? 'limited' : 'default'}>
                            {flag.level} risk
                          </Badge>
                          <span className="font-medium">{flag.title}</span>
                        </div>
                        <p className="text-slate-500 ml-0">{flag.explanation}</p>
                        {flag.page > 0 && <p className="text-slate-400 text-xs">Page {flag.page}</p>}
                      </li>
                    ))}
                  </ul>
                </section>
              )}
            </>
          )}

          {questions && questions.length > 0 && (
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-4 border-b pb-2">Your Questions &amp; Answers</h2>
              <div className="space-y-4">
                {questions.map((q, i) => (
                  <div key={q.id} className="border border-slate-200 rounded-lg p-4 text-sm">
                    <p className="font-medium text-slate-900 mb-1">Q: {q.question_text}</p>
                    <Badge variant={
                      q.answer_json.shortAnswer === 'May be covered' ? 'covered' :
                      q.answer_json.shortAnswer === 'May not be covered' ? 'excluded' : 'limited'
                    } className="mb-2">
                      {q.answer_json.shortAnswer}
                    </Badge>
                    <p className="text-slate-600">{q.answer_json.plainEnglishExplanation}</p>
                  </div>
                ))}
              </div>
            </section>
          )}

          <div className="border-t border-slate-200 pt-6">
            <p className="text-xs text-slate-400 leading-relaxed">{DISCLAIMER}</p>
          </div>
        </div>

        <div className="mt-6 print:hidden">
          <DisclaimerBanner />
        </div>
      </div>
    </div>
  )
}
