import type { Policy, PolicySummary } from '@/types'

export const DEMO_POLICY_ID = 'demo-acme-renters-2026'

export const DEMO_POLICY: Policy = {
  id: DEMO_POLICY_ID,
  user_id: 'demo',
  file_url: '',
  policy_nickname: 'Acme Renters Insurance 2026 (Demo)',
  policy_type: 'renters',
  jurisdiction: 'UK',
  owner_type: 'renter',
  insurer_name: 'Acme Insurance Ltd',
  policyholder_name: 'Jane Demo Smith',
  start_date: '2026-01-01',
  end_date: '2026-12-31',
  status: 'ready',
  processing_error: null,
  total_pages: 18,
  uploaded_at: new Date().toISOString(),
}

export const DEMO_SUMMARY: PolicySummary = {
  id: 'demo-summary',
  policy_id: DEMO_POLICY_ID,
  overview_json: {
    policy_type: 'Renters / Contents Insurance',
    insurer: 'Acme Insurance Ltd',
    policyholder: 'Jane Demo Smith',
    policy_period: '1 January 2026 to 31 December 2026',
    jurisdiction: 'UK',
    confidence: 'High',
  },
  coverage_json: [
    {
      title: 'Contents Cover',
      status: 'Covered',
      explanation: 'Your personal belongings inside your home are covered up to £5,000 in total for loss, theft, or damage.',
      page: 4,
      section: 'Section 2 – Contents Cover',
      quote: 'We cover loss or damage to your household contents',
      confidence: 'High',
    },
    {
      title: 'Personal Possessions Cover',
      status: 'Covered',
      explanation: 'Items taken outside the home (such as your phone, laptop, or jewellery) are covered up to £1,500 per single item.',
      page: 7,
      section: 'Section 3 – Personal Possessions',
      quote: 'personal possessions are covered away from home',
      confidence: 'High',
    },
    {
      title: 'Accidental Damage',
      status: 'Limited',
      explanation: 'Accidental damage to contents is covered only if you selected this as an optional add-on at the time of purchase.',
      page: 5,
      section: 'Section 2 – Contents Cover',
      quote: 'accidental damage is available as an optional extension',
      confidence: 'Medium',
    },
    {
      title: 'Liability Cover',
      status: 'Covered',
      explanation: 'Personal liability cover up to £1,000,000 if you accidentally injure someone or damage their property.',
      page: 12,
      section: 'Section 5 – Liability',
      quote: 'up to £1,000,000 for personal liability claims',
      confidence: 'High',
    },
    {
      title: 'Home Emergency',
      status: 'Covered',
      explanation: 'Emergency assistance is provided for sudden failures such as a burst pipe, boiler breakdown, or lost keys.',
      page: 14,
      section: 'Section 6 – Home Emergency',
      quote: 'emergency assistance is available 24 hours a day',
      confidence: 'High',
    },
  ],
  exclusions_json: [
    {
      title: 'Unattended Items',
      status: 'Excluded',
      explanation: 'Items left unattended in a public place are not covered. For example, a laptop left on a café table while you went to the toilet.',
      page: 9,
      section: 'Section 4 – Exclusions',
      quote: 'we do not cover items left unattended in a public place',
      confidence: 'High',
    },
    {
      title: 'Business Use',
      status: 'Excluded',
      explanation: 'Items used for any business purpose are excluded from the personal possessions cover.',
      page: 9,
      section: 'Section 4 – Exclusions',
      quote: 'items used for business or commercial purposes are excluded',
      confidence: 'High',
    },
    {
      title: 'Wear and Tear',
      status: 'Excluded',
      explanation: 'Gradual deterioration, wear and tear, or mechanical breakdown are not covered.',
      page: 10,
      section: 'Section 4 – Exclusions',
      quote: 'damage caused by wear and tear is not covered',
      confidence: 'High',
    },
    {
      title: 'Items Left in Vehicles',
      status: 'Excluded',
      explanation: 'Belongings left in an unattended vehicle are not covered unless locked in a concealed compartment.',
      page: 10,
      section: 'Section 4 – Exclusions',
      quote: 'items left in an unattended vehicle are not insured',
      confidence: 'High',
    },
    {
      title: 'High-Value Items Over Single Item Limit',
      status: 'Excluded',
      explanation: 'Any single item worth more than £1,500 is not covered unless separately listed and agreed by Acme.',
      page: 8,
      section: 'Section 3 – Personal Possessions',
      quote: 'items exceeding the single article limit require separate declaration',
      confidence: 'High',
    },
  ],
  limits_json: [
    { title: 'Total Contents Limit', amount: '£5,000', context: 'Maximum payout for all contents claims combined', page: 4, section: 'Section 2' },
    { title: 'Single Item Limit', amount: '£1,500', context: 'Maximum payout for any one item under personal possessions', page: 7, section: 'Section 3' },
    { title: 'Liability Cover', amount: '£1,000,000', context: 'Maximum personal liability payout', page: 12, section: 'Section 5' },
    { title: 'Voluntary Excess', amount: '£150', context: 'The amount you must pay towards each claim', page: 3, section: 'Policy Schedule' },
    { title: 'Compulsory Excess', amount: '£50', context: 'Mandatory excess applied by Acme to all claims', page: 3, section: 'Policy Schedule' },
    { title: 'Cash Cover Limit', amount: '£300', context: 'Maximum cover for cash in the home', page: 6, section: 'Section 2' },
  ],
  risk_flags_json: [
    {
      level: 'High',
      title: 'Unattended Items Exclusion',
      explanation: 'One of the most common reasons claims are rejected. If you leave a bag, phone, or laptop unattended — even for a moment — in a public place, you will not be covered.',
      quote: 'items left unattended in a public place are not covered',
      page: 9,
      section: 'Section 4 – Exclusions',
      questionToAsk: 'What exactly counts as "unattended" and does it matter if I left it for 30 seconds vs 5 minutes?',
    },
    {
      level: 'High',
      title: 'Business Use Exclusion',
      explanation: 'If you work from home or use your laptop for freelance work, those items may be excluded from your personal possessions cover. Many people do not realise this.',
      quote: 'items used for business or commercial purposes are excluded',
      page: 9,
      section: 'Section 4 – Exclusions',
      questionToAsk: 'Am I covered for my laptop if I use it partly for freelance work?',
    },
    {
      level: 'Medium',
      title: 'Single Item Limit of £1,500',
      explanation: 'Expensive items like MacBook Pros, high-end cameras, or engagement rings may be worth more than £1,500. Anything above this limit is only covered if separately declared.',
      quote: 'items exceeding the single article limit require separate declaration',
      page: 8,
      section: 'Section 3 – Personal Possessions',
      questionToAsk: 'How do I add high-value items to the policy, and is there an additional premium?',
    },
    {
      level: 'Medium',
      title: 'Combined Excess of £200',
      explanation: 'Your total excess (voluntary £150 + compulsory £50) means you pay the first £200 of any claim. For small claims, this may make it not worth claiming.',
      quote: 'voluntary excess and compulsory excess apply to all claims',
      page: 3,
      section: 'Policy Schedule',
      questionToAsk: 'Does making a small claim affect my future premiums even if it was less than the excess?',
    },
    {
      level: 'Low',
      title: 'Accidental Damage is Optional',
      explanation: 'Accidental damage is not included by default. If you did not select it as an add-on, you are not covered for, say, dropping your phone or spilling coffee on your laptop.',
      quote: 'accidental damage is available as an optional extension',
      page: 5,
      section: 'Section 2 – Contents Cover',
      questionToAsk: 'Can I add accidental damage cover mid-policy and what would the extra cost be?',
    },
  ],
  generated_at: new Date().toISOString(),
}

export const DEMO_CHUNKS = [
  { page_number: 4, section_title: 'Section 2 – Contents Cover', clause_reference: '2.1', chunk_text: 'We cover loss or damage to your household contents caused by fire, flood, theft, or accidental damage (if selected). The total limit for contents is £5,000.' },
  { page_number: 7, section_title: 'Section 3 – Personal Possessions', clause_reference: '3.1', chunk_text: 'Your personal possessions are covered away from home worldwide, up to the single article limit of £1,500 per item. Items must be owned by you or your family.' },
  { page_number: 9, section_title: 'Section 4 – Exclusions', clause_reference: '4.1', chunk_text: 'We do not cover items left unattended in a public place. We do not cover items used for business or commercial purposes. We do not cover damage caused by wear and tear.' },
  { page_number: 10, section_title: 'Section 4 – Exclusions', clause_reference: '4.2', chunk_text: 'Items left in an unattended vehicle are not insured unless locked in a concealed compartment. Valuables left visible in vehicles are excluded at all times.' },
  { page_number: 12, section_title: 'Section 5 – Liability', clause_reference: '5.1', chunk_text: 'We will pay up to £1,000,000 for personal liability claims arising from accidental injury to third parties or accidental damage to third-party property.' },
  { page_number: 14, section_title: 'Section 6 – Home Emergency', clause_reference: '6.1', chunk_text: 'Emergency assistance is available 24 hours a day, 7 days a week for sudden and unforeseen events such as burst pipes, boiler failure, or loss of keys.' },
  { page_number: 3, section_title: 'Policy Schedule', clause_reference: null, chunk_text: 'Compulsory excess: £50. Voluntary excess: £150. Total excess per claim: £200. Your policy number is AC-2026-DEMO-001. Policy period: 1 January 2026 to 31 December 2026.' },
  { page_number: 8, section_title: 'Section 3 – Personal Possessions', clause_reference: '3.3', chunk_text: 'Items exceeding the single article limit of £1,500 require separate declaration and agreement by Acme Insurance. Please contact us to add high-value items to your schedule.' },
  { page_number: 5, section_title: 'Section 2 – Contents Cover', clause_reference: '2.3', chunk_text: 'Accidental damage to contents is available as an optional extension. If you have not selected this add-on, accidental damage is not covered under this policy.' },
  { page_number: 6, section_title: 'Section 2 – Contents Cover', clause_reference: '2.5', chunk_text: 'Cash in the home is covered up to a maximum of £300. Coins, banknotes, and vouchers are included. Cash stored in a safe or locked drawer is covered up to this limit.' },
  { page_number: 15, section_title: 'Section 7 – Making a Claim', clause_reference: '7.1', chunk_text: 'To make a claim, notify us within 30 days of the incident. Call 0800-ACME-CLAIMS or visit our website. For theft, provide a crime reference number from the police.' },
  { page_number: 16, section_title: 'Section 8 – General Conditions', clause_reference: '8.1', chunk_text: 'You must take reasonable steps to prevent loss or damage. Failure to maintain security or take precautions may result in a claim being reduced or rejected.' },
]
