import Link from 'next/link'
import { Shield } from 'lucide-react'
import { DISCLAIMER } from '@/lib/utils'

export const metadata = { title: 'Terms of Service — Understand Cover' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F8FAFC]">
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Link href="/" className="inline-flex items-center gap-2 text-blue-700 font-bold text-lg">
            <Shield className="h-5 w-5" />
            Understand Cover
          </Link>
        </div>
      </div>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-8">Last updated: May 2026</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8 text-sm text-amber-800">
          <strong>Important:</strong> {DISCLAIMER}
        </div>

        <div className="space-y-8 text-sm text-slate-600">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. What Understand Cover is</h2>
            <p>Understand Cover is an educational tool that helps you understand the wording of your insurance policy in plain English. It explains what policy documents say — it does not provide legal, insurance, financial, or claims management advice.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. What Understand Cover is not</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Not an insurance broker or intermediary</li>
              <li>Not a law firm or legal adviser</li>
              <li>Not a claims management company</li>
              <li>Not a financial adviser</li>
              <li>Not regulated by the FCA for insurance distribution or advice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Acceptable use</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>You must only upload documents you have the right to share</li>
              <li>Do not upload documents containing other people&apos;s personal data without their consent</li>
              <li>Do not attempt to circumvent rate limits or access controls</li>
              <li>Do not use the service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. No guarantee of accuracy</h2>
            <p>AI-generated explanations may contain errors. We make reasonable efforts to ensure accuracy (including citation verification), but we cannot guarantee that every explanation is correct or complete. Always verify important information with your insurer, broker, or a qualified adviser.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Limitation of liability</h2>
            <p>Understand Cover is not liable for any loss or damage arising from reliance on explanations generated by this service, including claim decisions, coverage disputes, or financial loss. Our liability is limited to the maximum extent permitted by law.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Free tier limits</h2>
            <p>Free accounts are limited to 3 policies, 20MB per PDF, and 20 questions per policy per month. These limits may change. We will give reasonable notice of any changes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Governing law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the English courts.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Changes to these terms</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Contact</h2>
            <p>Questions? Email <a href="mailto:hello@understandcover.co.uk" className="text-blue-600 hover:underline">hello@understandcover.co.uk</a>.</p>
          </section>
        </div>

        <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 mt-8">
          <p className="text-xs text-slate-400">{DISCLAIMER}</p>
        </div>
      </div>
    </div>
  )
}
